name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "feature" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests defined"

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 50.19.67.76
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user

            # install git/node if missing
            sudo dnf install -y git nodejs npm

            # clone repo if not exists
            if [ ! -d "env-welcome" ]; then
              git clone -b main https://github.com/laiba357/Github-Action-CI-CD-.git env-welcome
            fi

            cd env-welcome
            git fetch --all
            git reset --hard origin/main

            npm install
            sudo npm install -g pm2

            # restart the app
            pm2 restart env-welcome || PORT=3000 pm2 start app.js --name env-welcome
