name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "feature" ]
  push:
    branches: [ "main" ]

jobs:
  # CI Job: Runs on pull requests to feature branch
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  # CD Job: Runs on push to main branch
  cd:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user

            # Clone repo if missing
            if [ ! -d "env-welcome" ]; then
              git clone -b main git@github.com:laiba357/Github-Action-CI-CD-.git env-welcome
            fi

            cd env-welcome
            git fetch --all
            git reset --hard origin/main

            # Install dependencies
            npm install

            # Restart app with PM2
            pm2 restart env-welcome || PORT=3000 ENV=dev pm2 start app.js --name env-welcome
