name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "feature" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build (optional)
        run: npm run build || echo "No build step defined"

      - name: Run tests (optional)
        run: npm test || echo "No tests defined"

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via HTTP to EC2
        run: |
          echo "Connecting to EC2 via HTTP..."

          # SSH into EC2 and deploy via HTTP clone/pull
          ssh -o StrictHostKeyChecking=no ec2-user@50.19.67.76 << 'EOF'
            cd /home/ec2-user

            # Install git and node if missing
            sudo dnf install -y git nodejs npm

            # Clone repo if not exists
            if [ ! -d "env-welcome" ]; then
              git clone -b main https://github.com/laiba357/Github-Action-CI-CD-.git env-welcome
            fi

            cd env-welcome
            git fetch --all
            git reset --hard origin/main

            npm install

            # Restart the app
            sudo npm install -g pm2
            pm2 restart env-welcome || PORT=3000 pm2 start app.js --name env-welcome
          EOF
