name: CI/CD Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to Dev EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            if [ ! -d "env-welcome" ]; then
              git clone -b develop https://github.com/laiba357/Github-Action-CI-CD-.git env-welcome
            fi
            cd env-welcome
            git fetch --all
            git reset --hard origin/develop
            npm install
            pm2 restart env-welcome-dev || PORT=3000 ENV=dev pm2 start app.js --name env-welcome-dev
