name: CI/CD Pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (optional, remove if none)
      - name: Run tests
        run: |
          if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then
            npm test
          else
            echo "No test script found, skipping."
          fi

      # Step 5: Deploy to EC2
      - name: Deploy to Dev EC2
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEV_EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            if [ ! -d "env-welcome" ]; then
              git clone -b develop https://github.com/laiba357/Github-Action-CI-CD-.git env-welcome
            fi
            cd env-welcome
            git fetch --all
            git reset --hard origin/develop
            npm install
            pm2 restart env-welcome-dev || PORT=3000 ENV=dev pm2 start app.js --name env-welcome-dev
